talkers:
  - dan
  - emma
  - kerry
  - mark
keywords:
  - cars
  - crown
  - dog
  - duck
  - fish
  - game
  - girl
  - hook
  - horse
  - line
  - man
  - near
  - nest
  - noise
  - nose
  - peas
  - soup
  - stairs
exampleWords:
  - ball
  - bears
  - bees
  - bike
  - bin
  - book
  - boys
  - cake
  - card
  - cat
  - clock
  - coat
  - coin
  - cot
  - cup
  - food
  - foot
  - gate
  - gears
  - hat
  - house
  - kite
  - knife
  - leg
  - loaf
  - mat
  - men
  - mouse
  - nurse
  - nuts
  - park
  - paws
  - pears
  - pin
  - pot
  - ring
  - road
  - room
  - seed
  - shark
  - shirt
  - skirt
  - spade
  - squares
  - suit
  - tears
  - teeth
  - ten
  - toys
  - wood
