
export const arpa_to_description_map = {
    "p":  "voiceless bilabial plosive",
    "b":  "voiced bilabial plosive",
    "t":  "voiceless alveolar plosive",
    "d":  "voiced alveolar plosive",
    "k":  "voiceless velar plosive",
    "g":  "voiced velar plosive",
    "m":  "voiced bilabial nasal",
    "n":  "voiced alveolar nasal",
    "l":  "lateral approximant",
    "r":  "alveolar approximant",
    "f":  "voiceless labiodental fricative",
    "v":  "voiced labiodental fricative",
    "th": "voiceless dental fricative",
    "dh": "voiced dental fricative",
    "s":  "voiceless alveolar fricative",
    "z":  "voiced alveolar fricative",
    "ng": "voiced velar nasal",
    "sh": "voiceless postalveolar fricative",
    "zh": "voiced postalveolar fricative",
    "y":  "voiced palatal approximant",
    "w":  "voiced labial-velar approximant",
    "hh": "voiceless glottal fricative",
    "ch": "voiceless postalveolar affricate",
    "jh": "voiced postalveolar affricate",
    "iy": "front close unrounded",
    "aa": "back open unrounded",
    "ao": "back open-mid rounded",
    "ia": "near-front near-close unrounded; central mid rounded",
    "ae": "front near-open unrounded",
    "eh": "fronr open-mid",
    "oh": "back open rounded",
    "ah": "back open-mid unrounded",
    "uw": "back close rounded",
    "ea": "front close-mid unrouned; central mid rounded",
    "ow": "central mid rounded; near-back near-close rounded",
    "ih": "near-front near-close unrounded",
    "ay": "front open unrounded; near-front near-close unrounded",
    "ua": "near-back near close rounded; central mid unrounded",
    "ey": "front close-mid unrounded; near-front near-close unrounded",
    "uh": "near-back near-close rounded",
    "oy": "back open-mid rounded; near-front near-close unrounded",
    "ax": "central mid unrounded",
    "aw": "front open unrounded ; near-back near-close rounded",
    "er": "central open-mid unrounded",
}

export const arpa_ipa_map = {
    "p": "p",
    "b": "b",
    "t": "t",
    "d": "d",
    "k": "k",
    "g": "g",
    "m": "m",
    "n": "n",
    "l": "l",
    "r": "ɹ",
    "f": "f",
    "v": "v",
    "th": "θ",
    "dh": "ð",
    "s": "s",
    "z": "z",
    "ng": "ŋ",
    "sh": "ʃ",
    "zh": "ʒ",
    "y": "j",
    "w": "w",
    "hh": "h",
    "ch": "tʃ",
    "jh": "dʒ",
    "iy": "i",
    "aa": "ɑ",
    "ao": "ɔ",
    "ia": "ɪə",
    "ae": "æ",
    "eh": "ɛ",
    "oh": "ɒ",
    "ah": "ʌ",
    "uw": "u",
    "ea": "eə",
    "ow": "əʊ",
    "ih": "ɪ",
    "ay": "aɪ",
    "ua": "ʊə",
    "ey": "eɪ",
    "uh": "ʊ",
    "oy": "ɔɪ",
    "ax": "ə",
    "aw": "aʊ",
    "er": "ɜ"
}
