fs = require('fs-extra')
fs.ensureDirSync('src/assets/images')
fs.ensureDirSync('src/assets/images/avatars')
fs.ensureDirSync('src/assets/images/words')
fs.ensureDirSync('src/assets/video')
fs.ensureDirSync('src/assets/audio')
